package com.github.wigggy.charlesschwab_api.data_objs


/** All dollar values are multiplied by 100 already. No need to x100 ANY values for this quote */
data class OptionQuote(
    val assetMainType: String,
    val realtime: Boolean,
    val ssid: Long,
    val symbol: String,

    val weekHigh52: Double,
    val weekLow52: Double,
    val askPrice: Double,
    val askSize: Int,
    val bidPrice: Double,
    val bidSize: Int,
    val closePrice: Double,
    val delta: Double,
    val gamma: Double,
    val highPrice: Double,
    val indAskPrice: Double,
    val indBidPrice: Double,
    val indQuoteTime: Long,
    val impliedYield: Double,
    val lastPrice: Double,
    val lastSize: Int,
    val lowPrice: Double,
    val mark: Double,
    val markChange: Double,
    val markPercentChange: Double,
    val moneyIntrinsicValue: Double,
    val netChange: Double,
    val netPercentChange: Double,
    val openInterest: Int,
    val openPrice: Double,
    val quoteTime: Long,
    val rho: Double,
    val securityStatus: String,
    val theoreticalOptionValue: Double,
    val theta: Double,
    val timeValue: Double,
    val totalVolume: Int,
    val tradeTime: Long,
    val underlyingPrice: Double,
    val vega: Double,
    val volatility: Double,

    val contractType: String,
    val daysToExpiration: Int,
    val deliverables: String,
    val description: String,
    val exchange: String,
    val exchangeName: String,
    val exerciseType: String,
    val expirationDay: Int,
    val expirationMonth: Int,
    val expirationType: String,
    val expirationYear: Int,
    val isPennyPilot: Boolean,
    val lastTradingDay: Long,
    val multiplier: Double,
    val settlementType: String,
    val strikePrice: Double,
    val underlying: String

)
